spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ShoppingCart
    username: postgres
    password: 12345678
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
server:
  port: 8081